[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"  # Match OpenZeppelin's version
optimizer = true
optimizer_runs = 200
via_ir = true  # Enable IR-based code generation

[rpc_endpoints]
avalanche = "${AVALANCHE_RPC}"
